#!/usr/local/bin/php
<?php
/*==============================================================================
 *  Title      : Create application documentation
 *  Author     : Digger (c) SAD-Systems <http://sad-systems.ru>
 *  Created on : 03.10.2015
 *==============================================================================
 * Console script
 * to run from command line
 * -----------------------------------------------------------------------------
 */

chdir(dirname(__DIR__));

echo "\n";
echo "Create PHP docs:\n"
   . "----------------------------------\n";
system("doxygen config/doxygen.cfg");

echo "\n";
echo "Create Javascript docs:\n"
   . "----------------------------------\n";
system("jsdoc -c config/jsdoc-conf.json");
echo "\n";
echo "done\n";