#!/usr/local/bin/php
<?php
/*==============================================================================
 *  Title      : Creates application test skeletons
 *  Author     : Digger (c) SAD-Systems <http://sad-systems.ru>
 *  Created on : 06.10.2015
 *==============================================================================
 * Console script
 * to run from command line
 * -----------------------------------------------------------------------------
 */

//--- Load main config:

$config = require 'common.php';

//--- Generates tests skeletons:

try {
    
    //--- Set sub config:
    $basePath = $config['basePath']; //<- appTests config file need $basePath!!!
    //--- change current dir to $basePath:
    chdir($basePath);
    
    //--- Generate tests skeletons:
    $configTests = require $config['appTests'];
    $configTests['includeAutoloaderFileName'] = \digger\cradle\application\Starter::getAutoloaderFile();
    $autogen = new digger\cradle\tests\Autogen($configTests, true);
    //--- Out results:
    print_r($autogen->getResult());    
    
} catch (Exception $e) {
    echo "ERROR: " . $e->getMessage() . "\n";    
}