#!/usr/local/bin/php
<?php
/*==============================================================================
 *  Title      : Update components (NodeJS, Bower, Composer)
 *  Author     : Digger (c) SAD-Systems <http://sad-systems.ru>
 *  Created on : 03.10.2015
 *==============================================================================
 * Console script
 * to run from command line
 * -----------------------------------------------------------------------------
 */

$a = $argv[1];

$o = [
    'all',
    'node',
    'bower',
    'composer',
    'autoload',
];

if (!$a) {
    echo "Use options: \n\t". implode("\n\t", $o) . "\n";
    exit;
}

chdir(dirname(__DIR__));

if ($a==$o[1] || $a==$o[0]) { 
//--- Node modules update ------------------------------------------------------
    echo "\n";
    echo "NodeJS modules update:\n"
       . "----------------------------------\n";
    system("npm update");    
    
}

if ($a==$o[2] || $a==$o[0]) { 
//--- Bower components update --------------------------------------------------
    echo "\n";
    echo "Bower components update:\n"
       . "----------------------------------\n";
    system("bower update --allow-root");    
    
}

if ($a==$o[3] || $a==$o[0]) { 
//--- Composer update ----------------------------------------------------------
    if (!file_exists("composer.phar")) {
        echo "\n";
        echo "Installing the Composer:\n"
           . "----------------------------------\n";
        system("curl -sS https://getcomposer.org/installer | php");
    }
    
    echo "\n";
    echo "Composer self-update:\n"
       . "----------------------------------\n";
    system("php composer.phar self-update");    
    
    echo "\n";
    echo "Composer components update:\n"
       . "----------------------------------\n";
    system("php composer.phar update");    
    
}

if ($a==$o[4] || $a==$o[0]) { 
//--- Composer autoloader update -----------------------------------------------
    echo "\n";
    echo "Composer update autoload:\n"
       . "----------------------------------\n";
    system("php composer.phar dump-autoload");    
    
}

echo "done\n";